databases:
  - name: postgres
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: MAR
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 bash start
    region: frankfurt
    repo: https://github.com/SONIC-MUSIC-BOT/MAR     
    branch: master
    envVars:
      - key: MUSIC_BOT_NAME
        sync: false
      - key: API_ID 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: AUTO_LEAVING_ASSISTANT 
        value: False
      - key: STRING_SESSION
        sync: false
      - key: LOG_GROUP_ID  
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: UPSTREAM_BRANCH
        value: master 
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString   
    autoDeploy: false
